spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.application.name=flight-booking-backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${MAIL_FROM}
brevo.from.name=aerolink
logging.level.com.example.flight_booking_backend.security=DEBUG
logging.level.org.springframework.security=DEBUG
spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/flight-booking}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/flight-booking/protocol/openid-connect/certs}

frontend.url=${FRONTEND_URL:http://localhost:3000}
keycloak.admin.url=${KEYCLOAK_ADMIN_URL:http://localhost:8080}
keycloak.admin.realm=flight-booking
keycloak.frontend.client-id=aerolink-frontend
keycloak.admin.client-id=aerolink-backend
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}

duffel.api.key=${DUFFEL_API_KEY}
